#+TITLE: My Emacs Configuration
#+AUTHOR: Chris Liourtas
#+EMAIL: cliourtas@kracked.tech
#+OPTIONS: num:nil
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))

* Emacs
*Last export {{{latest-export-date}}} with {{{word-count}}} words.*
** Early initialization of Emacs (=early-init.el=)
This file follows a script like format and is just meant for
initializing important facts about the configuration.

For starters disabling the default package manager:
#+begin_src emacs-lisp :tangle "early-init.el"
  (setq package-enable-at-startup nil)
#+end_src
Then adding the need directories to =load-path=.
#+begin_src emacs-lisp :tangle "early-init.el"
  (add-to-list 'load-path
  	     (expand-file-name "core/" user-emacs-directory))
  (add-to-list 'load-path
  	     (expand-file-name "my-emacs-packages/" user-emacs-directory))
#+end_src
** The main initialization of Emacs (=init.el=)
*** User Options
All of the user options are defined under the emacs group
=my-emacs=. A group in emacs-lisp is just a way to organize metadata
for Emacs' customization system. By modifying these values via =M-x
customize= the user can easily manipulate My-Emacs' behavior. Things
that can be modified are:
    - Enabled/Disabled Features.
    - UI (User Interface).
To define the group we use the =defgroup= macro.
#+begin_src emacs-lisp :tangle "init.el"
  (defgroup my-emacs nil
   "User options for my-emacs."
    :group 'emacs
  )
#+end_src
**** Emacs Environment Options
The =my-emacs-bibliographies= defines the files
where the global bibliographies are stored.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-bibliography "~/Documents/Bibliography/global.bib"
    "Where org-roam notes live."
    :group 'my-emacs
    :type 'string
  )
#+end_src

#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-bibliography-search-dir "~/Documents/Bibliography/"
    "Where org-roam notes live."
    :group 'my-emacs
    :type 'directory
  )
#+end_src

#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-bibliography-dir "~/Documents/Bibliography"
    "Where org-roam notes live."
    :group 'my-emacs
    :type 'directory
  )
#+end_src

#+begin_src emacs-lisp :tangle "init.el" 
  (defcustom my-emacs-citar-bibliographies '("~/Documents/Bibliography/global.bib")
      "List of bibliography files for Citar."
      :group 'my-emacs
      :type '(repeat file)
    )
#+end_src

#+begin_src emacs-lisp :tangle "init.el" 
  (defcustom my-emacs-citar-notes-paths'("~/Documents/Notes/")
      "List of paths for Citar notes."
      :group 'my-emacs
      :type '(repeat file)
    )
#+end_src

#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-citar-library-paths '("~/Documents/Papers" "~/Documents/Books")
     "List of of library paths for Citar."
      :group 'my-emacs
      :type '(repeat file)
   )
#+end_src
The =my-emacs-notes-dir= defines the directory
where notes are going to be stored as defined in [[id:58aed539-b711-444f-aacc-7d936ec93c16][Org Roam]].
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-notes-dir "~/Documents/Notes"
    "Where org-roam notes live."
    :group 'my-emacs
    :type 'directory
  )
#+end_src
The =my-emacs-dailies-dir= defines the directory
where dailie notes are going to be stored as defined in [[id:58aed539-b711-444f-aacc-7d936ec93c16][Org Roam]].
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-dailies-dir "~/Documents/Dailies"
    "Where org-roam dailies live."
     :group 'my-emacs
     :type 'directory
  )
#+end_src
The =my-emacs-blog-url= defines the URL of your Wordpress blog's
=xmlrpc= file as defined in [[id:12db6dab-fef2-48dc-8d5f-bd10ee991a56][Org2Blog]].
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-blog-url "https://kracked.tech/xmlrpc.php"
    "The url of the blog to contact wordpress as defined in org2blog."
    :type 'string
  )
#+end_src
The =my-emacs-blog-name= defines the name of your Wordpress blog.
Its just an identifier as defined in [[id:12db6dab-fef2-48dc-8d5f-bd10ee991a56][Org2Blog]].
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-blog-name "kracked"
    "Identifier of blog."
    :type 'string
  )
#+end_src
The =my-emacs-blog-name= defines the domain of your Wordpress blog
defined in [[id:12db6dab-fef2-48dc-8d5f-bd10ee991a56][Org2Blog]].
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-blog-domain "kracked.tech"
    "Domain of blog.."
    :type 'string
  )
#+end_src
The =my-emacs-latex-png-dir= defines where [[id:02d5c601-ba6e-409f-89e4-0e928e8fc28a][org-latex-preview]] will
store the latex preview images.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-latex-png-dir "~/Documents/LatexPng/"
    "Where latex preview pngs are stored."
    :type 'directory
  )
#+end_src
**** User Interface Options
The =my-emacs-tool-bar= defines whether the toolbar
should appear or not.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-tool-bar -1
    "If non-nil, enable `tool-bar-mode`."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
The =my-emacs-menu-bar= defines whether the menubar
should appear or not.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-menu-bar -1
    "If non-nil, enable `menu-bar-mode`."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
The =my-emacs-scroll-bar= defines whether the scrollbar
should appear or not.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-scroll-bar -1
    "If non-nil, enable `scroll-bar-mode`."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
**** Feature Options
The =my-emacs-vim-scrolling= defines whether vim-like scrolling
should be enabled or not.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-vim-scrolling t
    "If non-nil, enable smooth scrolling, like vim."
     :group 'my-emacs
     :type 'boolean
  )
#+end_src
The =my-emacs-evil= defines whether [[id:1a2f1081-efdf-4a45-84c0-e0f46281a0fb][Evil Mode]] should be
enabled or not.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-evil t
      "If non-nil, enable evil mode for vim emulation."
       :group 'my-emacs
       :type 'boolean
  )
#+end_src
*** Variables
Directory that contains all of the =use-package= declarations.
#+begin_src emacs-lisp :tangle "init.el"
  (defvar my-emacs-packages-dir
    (concat user-emacs-directory "my-emacs-packages/")
    "Directory that contains all of the `USE-PACKAGE` declarations."
  )
#+end_src
Ordered priority of packages that must be loaded.
#+begin_src emacs-lisp :tangle "init.el"
  (defvar my-emacs-packages-priority
    '("my-emacs-general.el")
    "Basenames or regexps of packages files to load first (ordered)."
  )
#+end_src
*** Package Manager
This emacs configuration uses [[https://github.com/progfolio/elpaca][elpaca]] as its package manager (for
now). I have been thinking of switching to a manual approach but for
now this will do. This will clone elpaca into your =user-emacs-directory= under
the elpaca subdirectory, clone it and finally activate it.
#+begin_src emacs-lisp :tangle "init.el"
  (defvar elpaca-installer-version 0.11)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                :ref nil :depth 1 :inherit ignore
                                :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                :build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
         (build (expand-file-name "elpaca/" elpaca-builds-directory))
         (order (cdr elpaca-order))
         (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (<= emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
          (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                    ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                    ,@(when-let* ((depth (plist-get order :depth)))
                                                        (list (format "--depth=%d" depth) "--no-single-branch"))
                                                    ,(plist-get order :repo) ,repo))))
                    ((zerop (call-process "git" nil buffer t "checkout"
                                          (or (plist-get order :ref) "--"))))
                    (emacs (concat invocation-directory invocation-name))
                    ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                          "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                    ((require 'elpaca))
                    ((elpaca-generate-autoloads "elpaca" repo)))
              (progn (message "%s" (buffer-string)) (kill-buffer buffer))
            (error "%s" (with-current-buffer buffer (buffer-string))))
        ((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
  #+end_src
Then I enable use-package
#+begin_src emacs-lisp :tangle "init.el"
    (elpaca elpaca-use-package
      (elpaca-use-package-mode))
#+end_src
I use use-package for declaratively configuring emacs 
#+begin_src emacs-lisp :tangle "init.el"
  (use-package emacs
    :ensure nil
    :config
    (load "my-emacs-functions")
    (tool-bar-mode my-emacs-tool-bar)
    (menu-bar-mode my-emacs-menu-bar)
    (scroll-bar-mode my-emacs-scroll-bar)
    (my-emacs-vim-scrolling-mode my-emacs-vim-scrolling)
    (my-emacs-load-packages) 
    (display-line-numbers-mode nil)
    (set-face-attribute 'default nil :family "0xProtoNerdFont" :height 120)
  )
#+end_src
** Core Functions (=my-emacs-functions.el=)
This file contains functions that:
  - Have no dependencies.
  - Do not warrant a creation of a library and/or mode.
  - May or not be moved as a library and/or mode later.
*** TODO Vim Scrolling Mode
This is not a mode, its a function. It might be a good idea to make it
a minor mode later, so for now its marked as TODO.
#+begin_src emacs-lisp :tangle "core/my-emacs-functions.el" :mkdirp yes
  (defun my-emacs-vim-scrolling-mode (enable)
    "Enable or disable 'vim-like' smooth scrolling depending on ENABLE."
    (if enable (progn
  	       (setq scroll-step 1)
  	       (setq scroll-margin 1)
  	       (setq scroll-conservatively 9999)))
  )
#+end_src
*** TODO Load Package
Loading packages should be done in a fixed order since packages may depend on each other.
For example =general.el= should be loaded before =magit.el= since the latter depends on the former.
This code may look complicated so a description is warranted:
 1. First define a helper function =my-emacs--priority-match-p=.
   This function simply takes two strings =`FILE`= which is a
   full path to a file and =`PATTERN`= which is a regex string
   or just the file name.
    - If =`FILE`= is equal to =`PATTERN`= return =`TRUE`=
 2. Now define the loader =my-emacs-load-packages=. Declare
   variables:
    - =all= List of absolute paths to every =.el= file inside =my-emacs-packages-dir=.
    - =seen= A hash-table data structure created by =make-hash-table=.
    - =head= The *ORDERED* list of priority files. Initialized by
      looping =my-emacs-packages-priority= and =all=. If a string (file name)
      defined there is not in =seen= yet and matches a string in all its a
      package that needs priority. 
    - =tail= The possibly unordered list of non-prioritized files. Initialized
      by being the rest "seen" files.
    - =files= Concats the =head= and =tail=.
    Now everything is ordered.
 3. Loop through =files=, load everything.
#+begin_src emacs-lisp :tangle "core/my-emacs-functions.el"
  (defun my-emacs--priority-match-p (file pattern)
    (let ((name (file-name-nondirectory file)))
      (or (string= name pattern)
  	(string-match-p pattern name))))

  (defun my-emacs-load-packages (&optional nosort)
    "Load all '.el' files in `MY-EMACS-PACKAGES-DIR` honoring,
  `MY-EMACS-PACKAGES-PRIORITY`.If NOSORT is non-nil, do not sort the
  non-priority tail (raw FS order)."
    (let* ((all (directory-files my-emacs-packages-dir t "\\.el\\'" nosort))
           (seen (make-hash-table :test 'equal))
           (head (cl-loop for pat in my-emacs-packages-priority append
                          (cl-remove-if-not
                           (lambda (f)
                             (and (my-emacs--priority-match-p f pat)
                                  (not (gethash f seen))
                                  (prog1 t (puthash f t seen))))
                           all)))
           (tail (cl-remove-if (lambda (f) (gethash f seen)) all))
           (files (nconc head tail)))
      (dolist (f files)
        (condition-case err
            (load f nil 'nomessage)
          (error
           (message "[my-emacs] Failed to load %s: %s"
                    (file-name-nondirectory f) err))))))
#+end_src
** Packages
This section exports only =use-package= declarations for packages.
Everything that is not a use-package declaration should be in
=my-emacs-library=.
*** General
For key-binding management I use [[https://github.com/noctuid/general.el][general]]. It provides many
useful features for defining key-bindings. I mostly take advantage
of the =:general= keyword in use-package that comes with installing it.
Notice the =(elpaca-wait)= after the package declaration.
 - TODO I should probably find a way to use =general-create-definer= and then use it on use-package.
   perhaps create my own =use-package= keyword? This would allow for global usage of an "evil-leader"-like
   key and perhaps further customization for the user.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-general.el" :mkdirp yes
  (use-package general
    :ensure (:wait t)
    :demand t
    :config
    (general-auto-unbind-keys)
  )
#+end_src
*** Exec Path From Shell
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-exec-path-from-shell.el" :mkdirp yes
  (use-package exec-path-from-shell
    :ensure t
    :config
    (when (memq window-system '(mac ns x))
     (exec-path-from-shell-initialize))
    :custom
    (exec-path-from-shell-variables '("PATH" "MANPATH"))
  )
#+end_src
*** Direnv
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-direnv.el" :mkdirp yes
  (use-package direnv
    :ensure t
    :config
    (direnv-mode)
  )
#+end_src
*** Evil Mode
:PROPERTIES:
:ID:       1a2f1081-efdf-4a45-84c0-e0f46281a0fb
:END:
[[https://github.com/emacs-evil/evil][Evil]] provides a vim-motions emulation layer on top of emacs. This package
should only be loaded if =my-emacs-evil= variable is non-nil.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-evil.el" :mkdirp yes
  (use-package evil
    :ensure t
    :after general
    :if my-emacs-evil
    :custom (evil-want-keybinding nil)
    (evil-want-integration t)
    (evil-want-minibuffer t) 
    :config
    (evil-mode)
     :general (:keymaps 'evil-insert-state-map
  	    "C-k" nil
  	    "C-j" nil
  	    "C-h" nil
  	    "C-l" nil
  	    "C-d" nil
  	    "C-a" nil)
     (:keymaps 'evil-normal-state-map
  	     "C-." nil
  	      )
  )
#+end_src
[[https://github.com/emacs-evil/evil-collection][Evil-collection]] is a collection of evil bindings for the parts of Emacs that
evil does not cover properly by default.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-evil.el"
  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (evil-collection-init)
  )
#+end_src
[[https://github.com/redguardtoo/evil-nerd-commenter][Evil-Nerd-Commenter]] is just a quick and fancy way to comment code. It comes
with a few functions (no modes), but I just use =evilnc-comment-or-uncomment-lines=.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-evil.el"
  (use-package evil-nerd-commenter
    :ensure t
    :after evil
    :general
    (:keymaps 'evil-visual-state-map
  	    "gcc" 'evilnc-comment-or-uncomment-lines)
    (:keymaps 'evil-normal-state-map
  	    "gcc" 'evilnc-comment-or-uncomment-lines)
  )
#+end_src
[[https://github.com/emacs-evil/evil-surround][Evil-Surround]] is the evil equivelant of [[https://github.com/tpope/vim-surround][surround.vim]].
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-evil.el"
  (use-package evil-surround
    :ensure t
    :after evil
    :hook evil-mode
  )
#+end_src
[[https://github.com/emacsmirror/undo-fu][Undo-Fu]] provides undo-redo for Emacs.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-evil.el"
  (use-package undo-fu
    :ensure t
    :after evil
    :custom
    (evil-undo-system 'undo-fu)
  )
#+end_src
[[https://github.com/gabesoft/evil-mc][Evil-mc]] provides multi-cursor functionallity for emacs-evil.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-evil.el"
  (use-package evil-mc
    :ensure t
    :after evil
    :hook
    evil-mode
    :general
    (:keymaps 'evil-visual-state-map
  	    ",a" 'evil-mc-make-all-cursors
  	    )
    (:keymaps 'evil-normal-state-map
  	    ",d" 'evil-mc-undo-all-cursors
  	    ",r" 'evil-mc-resume-cursors
  	    ",p" 'evil-mc-pause-cursors
  	    ",m" 'evil-mc-make-cursor-here
  	    )

    (:keymaps 'evil-insert-state-map
  	    "M-, a" 'evil-mc-make-all-cursors
  	    "M-, d" 'evil-mc-undo-all-cursors
  	    "M-, r" 'evil-mc-resume-cursors
  	    "M-, p" 'evil-mc-pause-cursors
  	    "M-, m" 'evil-mc-make-cursor-here
  	    )
  )
#+end_src
*** TODO Magit
[[https://github.com/magit/magit][Magit]] is a wrapper around git. Notice the dependency on transient,
perhaps it should be enabled globally as a library from source so its marked as TODO.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-magit.el" :mkdirp yes
  (use-package transient
    :ensure t
    )

  (use-package magit
    :ensure t
    :general
    (:prefix "C-c m"
        "g" 'magit-status
        "i" 'magit-init
        "c" 'magit-clone)
  )
#+end_src
*** Dired
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-dired.el" :mkdirp yes
  (use-package dired
    :ensure nil
  )
#+end_src
*** ISpell
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-ispell.el" :mkdirp yes
  (use-package ispell
    :ensure nil 
    :custom
    (ispell-program-name "hunspell")
    (ispell-dictionary "en_US,el_GR") 
    :config
    (add-to-list 'ispell-hunspell-dictionary-alist
               '("en_US,el_GR"
                 "[[:alpha:]]"
                 "[^[:alpha:]]"
                 "['’]"
                 t
                 ("-d" "en_US,el_GR")
                 nil
                 utf-8)))
    :hook
    (latex-mode . flyspell-mode)
    (markdown-mode . flyspell-mode)
    (org-mode . flyspell-mode)
  )
#+end_src
*** Which-key
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-which-key.el" :mkdirp yes
  (use-package which-key
    :ensure nil
    :init
    (which-key-mode)
    :config 
    (which-key-setup-side-window-bottom)
    :custom
    (which-key-idle-delay 1)
    (which-key-idle-secondary-delay 0.05)
  )
#+end_src
*** Eglot
Eglot is the built in LSP server for Emacs.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-eglot.el" :mkdirp yes
  (use-package eglot
    :ensure nil
    :commands (eglot eglot-ensure)
    :config
    :init
    (setq eglot-autoshutdown t
          eglot-events-buffer-config 0
          eglot-sync-connect nil
          eglot-confirm-server-edits nil)
  )
#+end_src
*** Eldoc-Box
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-eldoc-box.el" :mkdirp yes
  (use-package eldoc-box
    :ensure t
    :init
    (add-hook 'eglot-managed-mode-hook #'eldoc-box-hover-mode t)
    (add-hook 'prog-mode-hook #'eldoc-box-hover-mode t)
  )
#+end_src
*** Flymake
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-flymake.el" :mkdirp yes
  (use-package flymake
    :ensure nil
    :custom
    (flymake-show-diagnostics-at-end-of-line 'fancy)
    :hook
    (prog-mode . flymake-mode)
  )
#+end_src
*** Org
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-org.el" :mkdirp yes
  (use-package org
    :ensure `(org :repo "https://code.tecosaur.net/tec/org-mode.git/"
  		:branch "dev"
  	   )
    :config
     (set-face-attribute 'org-block-begin-line nil :height 150)
     (org-babel-do-load-languages
      'org-babel-load-languages
      '((python . t)
        (haskell . t)
        (latex . t)
        (shell . t))
      )
    :custom
     (org-pretty-entities t)
     (fill-column 70)
    :hook
     (org-mode . auto-fill-mode)
     (org-mode . (lambda ()
  		   (font-lock-add-keywords
  		    nil
  		    '(
  		      ("^#\\+begin_src\\(.*\\)$"
  		       (0 (progn
  			    (compose-region (match-beginning 0) (+ (match-beginning 0) 11) "")
  			    nil)))))
  		   ))

  )
#+end_src
*** Org Roam
:PROPERTIES:
:ID:       58aed539-b711-444f-aacc-7d936ec93c16
:END:

[[https://github.com/org-roam/org-roam][Org-Roam]] is a note-taking tool.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-org-roam.el" :mkdirp yes
  (use-package org-roam
    :ensure t
    :init
    (setq org-roam-v2-ack t)
    (org-roam-db-sync)
    :custom
    (org-roam-node-display-template
        (concat "${title:*} "
                (propertize "${tags:10}" 'face 'org-tag)))
    (org-roam-directory my-emacs-notes-dir)
    (org-roam-dailies-directory  (file-truename my-emacs-dailies-dir))
    :config
    (require 'org-roam-export) 
    (org-roam-db-autosync-mode)
    :general
    (:prefix "C-c n"

  	   "D r" 'org-roam-db-sync
  	   
  	   "n i" 'org-roam-node-insert
  	   "n f" 'org-roam-node-find
  	   "n d" 'org-roam-node-remove

  	   "r i" 'org-roam-ref-add
  	   "r d"  'org-roam-ref-remove

  	   "t i" 'org-roam-tag-add
  	   "t d" 'org-roam-tag-remove

  	   "d i" 'org-roam-dailies-capture-today
  	   "d f" 'org-roam-dailies-goto-date
  ))
#+end_src
*** Org2Blog
:PROPERTIES:
:ID:       12db6dab-fef2-48dc-8d5f-bd10ee991a56
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-org2blog.el" :mkdirp yes
  (use-package org2blog
    :ensure t
    :commands (org2blog-user-interface)
    :config
    (org2blog-user-login)
    :preface
    (defun my-emacs-blog--creds ()
      (let* ((entry (car (auth-source-search
  			:host my-emacs-blog-domain
  			:require '(:user :secret))))
  	   (user (plist-get entry :user))
  	   (secret (plist-get entry :secret))
  	   (pass (if (functionp secret) (funcall secret) secret)))
        (list user pass)))
    (defun my-emacs-blog--run-after-save (post)
      (pp post)
    )
    :custom
    (org2blog/wp-blog-alist
     (let* ((creds (my-emacs-blog--creds))
  	  (user (car creds))
  	  (pass (cadr creds)))
       `((,my-emacs-blog-name
  	:url ,my-emacs-blog-url
  	:username ,user
  	:password ,pass))))
    (org2blog/wp-image-thumbnails t)
    (org2blog/wp-use-wp-latex t)
    (org2blog/wp-image-upload t)
    (org2blog/wp-show-post-in-browser 'show)
    :general
    (:prefix "C-c b" 
  	   "i"     'org2blog-user-interface
  	   "n"     'org2blog-buffer-new

  	   "b p"   'org2blog-buffer-post-publish
  	   "b s"   'org2blog-buffer-post-save 
  	   "b v"   'org2blog-buffer-post-view
  	   "b d"   'org2blog-buffer-post-trash

  	   "p p"   'org2blog-buffer-page-publish
  	   "p s"   'org2blog-buffer-page-save
  	   "p v"   'org2blog-buffer-page-view
  	   "p d"   'org2blog-buffer-page-trash
  	   )
    :hook
    (org2blog-buffer-entry-save . my-emacs-blog--run-after-save)
  )
#+end_src
*** Org Latex Preview
:PROPERTIES:
:ID:       02d5c601-ba6e-409f-89e4-0e928e8fc28a
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/org-latex-preview.el" :mkdirp yes
  (use-package org-latex-preview
    :ensure nil
    :config
    (plist-put org-latex-preview-appearance-options
             :page-width 0.8)
    :custom
    (org-latex-preview-mode-display-live t)
    (org-latex-preview-mode-update-delay 0.25)
    (org-latex-preview-ltxpng-directory my-emacs-latex-png-dir)
    (org-latex-create-formula-image-program 'dvisvgm)
    :hook
    (org-mode)
  )
#+end_src
*** Nerd Icons
:PROPERTIES:
:ID:       7acb8b56-d7df-4085-bfb5-8f765ee92c76
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-nerd-icons.el" :mkdirp yes
  (use-package nerd-icons
    :ensure t
  )
#+end_src
*** Ebib
:PROPERTIES:
:ID:       632416c5-a3da-48e5-83d9-5f34cc9f8f67
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-ebib.el" :mkdirp yes
  (use-package ebib
    :ensure t
    :custom
    (ebib-bibtex-dialect (car (cdr bibtex-dialect-list)))
    (ebib-bib-search-dirs my-emacs-bibliography-search-dir)
    (ebib-default-directory my-emacs-bibliography)
    (ebib-truncate-file-names nil)
  )
#+end_src
*** Citar
:PROPERTIES:
:ID:       06fae039-5c33-44e3-ba4c-9ddd19b194d8
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-citar.el" :mkdirp yes
  (use-package citar
    :ensure t
    :custom
    (citar-bibliography my-emacs-citar-bibliographies)
    (org-cite-global-bibliography my-emacs-citar-bibliographies)
    (citar-library-paths my-emacs-citar-library-paths)
    (citar-notes-paths my-emacs-citar-notes-paths)
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar)
    :hook
    (LaTeX-mode . citar-capf-setup)
    (org-mode . citar-capf-setup)
    :general
    (:prefix "C-c n"
             "p o" 'citar-open
             "p n" 'citar-open-note
             "p f" 'citar-open-file
             "p l" 'citar-open-links
             "p N" 'citar-open-notes
    )
  )
#+end_src
*** Citar-Embark
:PROPERTIES:
:ID:       aefa8972-f577-4d34-82bb-a67d5584481a
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-citar-embark.el" :mkdirp yes
  (use-package citar-embark
    :ensure t
    :after (citar embark)
    :config
    (citar-embark-mode)
  )
#+end_src
*** Citar-Org-Roam
:PROPERTIES:
:ID:       be672102-60b7-4866-b0f8-99acc9a8f844
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-citar-org-roam.el" :mkdirp yes
  (use-package citar-org-roam
    :ensure t
    :after (citar org-roam)
    :config
    (citar-org-roam-mode)
  )
#+end_src
*** Embark && Consult
:PROPERTIES:
:ID:       2df2306f-5a57-4f3d-9f50-40f94d8459bc
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-consult.el" :mkdirp yes
  (use-package embark-consult
    :ensure t
  )
#+end_src
**** Consult
:PROPERTIES:
:ID:       f4c474be-976b-402c-8239-df92b7c9fa4f
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-consult.el" :mkdirp yes
  (use-package consult 
    :ensure t
    :general
    ("C-x b" 'consult-buffer)
    ("C-x v r" 'consult-register)
    ("C-x r s" 'consult-register-store)
    ("C-x r l" 'consult-register-load) 
    ("C-x v M"    'consult-global-mark)
    ("C-x v m"    'consult-mark)
    ("C-x C-f" 'consult-find)
    ("M-g g" 'consult-goto-line)
    ("M-g i" 'consult-imenu)
    ("M-g p" 'consult-imenu-multi)
    ("M-g m" 'consult-outline)
    ("M-g f" 'consult-flymake)
    ("M-g c" 'consult-compile-error)
    ("M-s l" 'consult-line)
    ("M-s L" 'consult-line-multi)
    ("M-s g" 'consult-ripgrep)
  )
  :config
  (setq consult-async-min-input 1)
#+end_src
**** Embark
:PROPERTIES:
:ID:       9460042b-f35e-4cee-9ac1-092651f2e905
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-embark.el" :mkdirp yes
  (use-package embark
    :ensure t
    :general
    ("C-." 'embark-act)
    ("C-;" 'embark-dwim)
  )
#+end_src
*** Project
:PROPERTIES:
:ID:       69ff5518-5561-427b-95cc-0784306c9082
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-project.el" :mkdirp yes
  (use-package project
    :ensure nil
  )
#+end_src
*** Themes
:PROPERTIES:
:ID:       c14ce9c6-3e64-4379-9ecc-3496f820c091
:END:
**** Ef
:PROPERTIES:
:ID:       702d2015-a26e-4074-9059-dc1c657c0404
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-ef-theme.el" :mkdirp yes
  (use-package ef-themes
    :ensure t
    :init
    (ef-themes-take-over-modus-themes-mode 1)
    :custom 
    (modus-themes-mixed-fonts t)
    (modus-themes-italic-constructs t)
    :config
    (modus-themes-load-theme 'ef-light)
    )
#+end_src
*** Autocompletion
:PROPERTIES:
:ID:       5508413d-791d-4107-a7a0-265daadf1b64
:END:
Vertico offers, vertical autocompletions on the minibuffer.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-vertico.el" :mkdirp yes
  (use-package vertico
    :ensure t
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode) 
    :general
    (
     :keymaps 'vertico-map
  	    "C-k" 'vertico-previous
  	    "C-j" 'vertico-next
    )
  )
#+end_src
Marginalia offers comments right next to the commands on the minibuffer.
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-marginalia.el" :mkdirp yes
  (use-package marginalia
    :ensure t
    :init
    (marginalia-mode)
  )
#+end_src

#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-corfu.el" :mkdirp yes
  (use-package corfu
    :ensure t
    :init
    (global-corfu-mode)
    :general (:keymaps 'corfu-map
  	    "C-k" 'corfu-previous
  	    "C-j" 'corfu-next
  	    "C-d" 'corfu-info-documentation
  	    "C-a" 'corfu-info-location
  	    "C-h" 'corfu-quit
  	    "C-l" 'corfu-insert
  	    "C-m" 'corfu-move-to-minibuffer)
    ("C-l" 'completion-at-point)
  )
#+end_src

#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-dabbrev.el" :mkdirp yes
  (use-package dabbrev
    :ensure nil
    :bind (("C-M-/" . dabbrev-expand))
    :config
    (add-to-list 'dabbrev-ignored-buffer-regexps "\\` ")
    (add-to-list 'dabbrev-ignored-buffer-modes 'doc-view-mode)
    (add-to-list 'dabbrev-ignored-buffer-modes 'pdf-view-mode)
    (add-to-list 'dabbrev-ignored-buffer-modes 'tags-table-mode)
  )
#+end_src

#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-cape.el" :mkdirp yes
  (use-package cape
    :ensure t
    :init
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-elisp-block)
    (add-hook 'completion-at-point-functions #'cape-history)
    (add-hook 'completion-at-point-functions #'cape-abbrev)
    (add-hook 'completion-at-point-functions #'cape-dict)
    (add-hook 'completion-at-point-functions #'cape-elisp-block)
    (add-hook 'completion-at-point-functions #'cape-keyword)
    (add-hook 'completion-at-point-functions #'cape-tex)
  )
#+end_src

#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-kind-icon.el" :mkdirp yes
  (use-package kind-icon
    :ensure t
    :after corfu
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+end_src

#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-orderless.el" :mkdirp yes
  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless partial-completion basic))
    (completion-category-defaults nil)
    (completion-category-overrides nil)
  )
#+end_src
*** Email
:PROPERTIES:
:ID:       b199f3cd-bc96-4140-b725-4ca320e90998
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-email.el" :mkdirp yes
  (use-package notmuch
    :ensure t
    :config
    (setq send-mail-function 'sendmail-send-it
      sendmail-program "/usr/bin/msmtp"
      mail-specify-envelope-from t
      message-sendmail-envelope-from 'header
      mail-envelope-from 'header)
    (setq notmuch-fcc-dirs nil)
  )
#+end_src
*** Org-Mime
:PROPERTIES:
:ID:       fea4ce12-bf6d-4e2b-a26a-80290f59d61d
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-org-mime.el" :mkdirp yes
  (use-package org-mime
    :ensure t 
  )
#+end_src
*** Programming Languages
:PROPERTIES:
:ID:       aded49c3-48a3-462a-8f24-abeb5bae2eb6
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-rust.el" :mkdirp yes
  (use-package prog-mode
    :ensure nil
    :custom
    (display-line-numbers-type 'relative)
    (fill-column 100)
    :hook
    (prog-mode . display-line-numbers-mode)
    (prog-mode . auto-fill-mode)
  )
#+end_src
**** Rust
:PROPERTIES:
:ID:       df45555c-c0db-4a4e-acfe-80d8b1613896
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-rust.el" :mkdirp yes
  (use-package rustic
    :ensure t
    :custom
    (rustic-lsp-client 'eglot)
    :hook
    (rustic-mode . eglot-ensure)
  )
#+end_src
**** Ocaml
:PROPERTIES:
:ID:       e7be6e66-5cbc-4476-8d0e-de5726cdc42b
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-ocaml.el" :mkdirp yes
  (use-package tuareg
    :ensure t
    :hook
    (tuareg-mode . eglot-ensure)
  )
#+end_src
**** Haskell
:PROPERTIES:
:ID:       a1cab303-6f5b-4057-8fc1-d222f931d16b
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-haskell.el" :mkdirp yes
  (use-package haskell-mode
    :ensure t
    :hook
    (haskell-mode . eglot-ensure)
  )
#+end_src
**** Python
:PROPERTIES:
:ID:       cd2a8f9c-1eb4-488b-b77b-e79c5b95b2f4
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-python.el" :mkdirp yes
  (use-package python-mode
    :ensure nil
    :hook
    (python-mode . eglot-ensure)
  )
#+end_src
**** C++
:PROPERTIES:
:ID:       97478dcf-d9c9-4816-ab7e-7469d41169e3
:END:
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-cpp.el" :mkdirp yes
  (use-package c++-mode
    :ensure nil
    :hook
    (c++-mode . eglot-ensure)
  )
#+end_src
**** GLSL
#+begin_src emacs-lisp :tangle "my-emacs-packages/my-emacs-glsl.el" :mkdirp yes
  (use-package glsl-mode
    :ensure t
  )
#+end_src
