#+TITLE: My Emacs Configuration
#+AUTHOR: Chris Liourtas
#+EMAIL: cliourtas@kracked.tech
#+OPTIONS: num:nil
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))

* Emacs
*Last export {{{latest-export-date}}} with {{{word-count}}} words.*
** Early initialization of Emacs (=early-init.el=)
#+begin_src emacs-lisp :tangle "early-init.el"
  (setq package-enable-at-startup nil)
#+end_src
** The main initialization of Emacs (=init.el=)
*** User Options
All of the user options are defined under the emacs group
=my-emacs=. A group in emacs-lisp is just a way to organize metadata
for Emacs' customization system. By modifying these values via =M-x
customize= the user can easily manipulate My-Emacs' behavior. Things
that can be modified are:
    - Theme-Families.
    - Enabled/Disabled Features.
    - UI (User Interface).
To define the group we use the =defgroup= macro.
#+begin_src emacs-lisp :tangle "init.el"
  (defgroup my-emacs nil
   "User options for my-emacs."
    :group 'emacs
  )
#+end_src
**** Theme Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-load-theme-family 'nano
    "Set of themes to load."
    :group 'my-emacs
    :type '(choice :tag "Set of themes to load" :value 'nano
  	 )
  )
#+end_src
**** User Interface Options
***** Dired Order Option
This is better explained in the Dired section.
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-dired-order '(dirs hidden-dirs files hidden-files)
    "The order of which dired displays its items.
  Each element should be one of the following symbols:
  - `dirs` : visible directories
  - `hidden-dirs` : hidden directories (starting with '.')
  - `files` : visible files
  - `hidden-files` : hidden files (starting with '.')"
    :group 'my-emacs
    :type '(repeat
  	  (choice (const dirs)
  		  (const hidden-dirs)
  		  (const files)
  		  (const hidden-files)))
  )
#+end_src
***** Tool-Bar Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-tool-bar -1
    "If non-nil, enable `tool-bar-mode`."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
***** Menu-Bar Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-menu-bar -1
    "If non-nil, enable `menu-bar-mode`."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
***** Scroll-Bar Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-scroll-bar -1
    "If non-nil, enable `scroll-bar-mode`."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
**** Feature Options
***** Vim Scrolling Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-vim-scrolling t
    "If non-nil, enable smooth scrolling, like vim."
     :group 'my-emacs
     :type 'boolean
  )
#+end_src
***** Evil Mode Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-evil t
      "If non-nil, enable evil mode for vim emulation."
       :group 'my-emacs
       :type 'boolean
  )
#+end_src
***** Rust Language Support
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-rust t
    "If non-nil, enable support for Rust."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
***** Ocaml Language Support
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-ocaml t
    "If non-nil, enable support for Ocaml."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
***** Haskell Language Support
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-haskell t
    "If non-nil, enable support for Haskell."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src
***** C/C++ Language Support
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-c-c++ t
    "If non-nil, enable support for C/C++."
    :group 'my-emacs
    :type 'boolean
  )
#+end_src

