#+TITLE: My Emacs Configuration
#+AUTHOR: Chris Liourtas
#+EMAIL: cliourtas@kracked.tech
#+OPTIONS: num:nil
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))

* Emacs
*Last export {{{latest-export-date}}} with {{{word-count}}} words.*
** Early initialization of Emacs (=early-init.el=)
#+begin_src emacs-lisp :tangle "early-init.el"
  (setq package-enable-at-startup nil)
#+end_src
** The main initialization of Emacs (=init.el=)
*** User Options
All of the user options are defined under the emacs group
=my-emacs=. A group in emacs-lisp is just a way to organize metadata
for Emacs' customization system. By modifying these values via =M-x
customize= the user can easily manipulate My-Emacs' behavior. Things
that can be modified are:
    - Theme-Families.
    - Enabled/Disabled Features.
    - UI (User Interface).
To define the group we use the =defgroup= macro.
#+begin_src emacs-lisp :tangle "init.el"
  (defgroup my-emacs nil
   "User options for my-emacs."
    :group 'emacs
  )
#+end_src
**** Theme Option
#+begin_src emacs-lisp :tangle "init.el"
  (defcustom my-emacs-load-theme-family 'nano
    "Set of themes to load."
    :group 'my-emacs
    :type '(choice :tag "Set of themes to load" :value 'nano
  	 )
  )
#+end_src
**** User Interface Options
***** Dired Order Option
***** Tool-Bar Option
***** Menu-Bar Option
***** Scroll-Bar Option
**** Feature Options
***** Vim Scrolling Option
***** Evil Mode Option
***** Rust Language Support
***** Ocaml Language Support
***** Haskell Language Support
***** C/C++ Language Support

